<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6527" started-at="2022-02-07T12:10:59 CET" finished-at="2022-02-07T12:11:05 CET">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6527" started-at="2022-02-07T12:10:59 CET" finished-at="2022-02-07T12:11:05 CET">
      <class name="d04_02_2022.Zadatak3">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:d04_02_2022.Zadatak3@63440df3]" name="beforeMethod" is-config="true" duration-ms="2460" started-at="2022-02-07T12:10:59 CET" finished-at="2022-02-07T12:11:01 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testSortByAge()[pri:0, instance:d04_02_2022.Zadatak3@63440df3]" name="testSortByAge" duration-ms="3407" started-at="2022-02-07T12:11:01 CET" finished-at="2022-02-07T12:11:05 CET">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at d04_02_2022.Zadatak3.testSortByAge(Zadatak3.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSortByAge -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:d04_02_2022.Zadatak3@63440df3]" name="afterMethod" is-config="true" duration-ms="624" started-at="2022-02-07T12:11:05 CET" finished-at="2022-02-07T12:11:05 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- d04_02_2022.Zadatak3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
